// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CleanFilesData, CleanFilesResponses, GetUnusedFilesData, GetUnusedFilesResponses, HealthCheckData, HealthCheckResponses, ScanFilesData, ScanFilesResponses } from './types.gen';
import { zCleanFilesBody, zCleanFilesResponse, zGetUnusedFilesResponse, zHealthCheckResponse, zScanFilesResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness check.
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zHealthCheckResponse.parseAsync(data),
    url: '/health',
    ...options
});

/**
 * List the cleanup candidates stored by the most recent scan.
 */
export const getUnusedFiles = <ThrowOnError extends boolean = false>(options?: Options<GetUnusedFilesData, ThrowOnError>): RequestResult<GetUnusedFilesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUnusedFilesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetUnusedFilesResponse.parseAsync(data),
    url: '/files/unused',
    ...options
});

/**
 * Trigger a fresh scan now, persist the results, and return them.
 */
export const scanFiles = <ThrowOnError extends boolean = false>(options?: Options<ScanFilesData, ThrowOnError>): RequestResult<ScanFilesResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ScanFilesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zScanFilesResponse.parseAsync(data),
    url: '/files/scan',
    ...options
});

/**
 * Clean the given files: remove matching torrents and delete orphans.
 */
export const cleanFiles = <ThrowOnError extends boolean = false>(options: Options<CleanFilesData, ThrowOnError>): RequestResult<CleanFilesResponses, unknown, ThrowOnError> => (options.client ?? client).post<CleanFilesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zCleanFilesBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zCleanFilesResponse.parseAsync(data),
    url: '/files/clean',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
