// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type HealthDto = {
    status: string;
};

export type ScannedFileDto = {
    /**
     * Absolute path to the file.
     */
    path: string;
    /**
     * File size in bytes.
     */
    sizeBytes: number;
    /**
     * Age in whole days, based on mtime.
     */
    ageDays: number;
    /**
     * Hardlink count. 1 = unused; > 1 = still in use.
     */
    links: number;
};

export type MatchedTorrentDto = {
    hash: string;
    name: string;
    /**
     * Path qBittorrent reports as the torrent content root.
     */
    contentPath: string;
    category: string;
    tags: Array<string>;
    sizeBytes: number;
};

export type CleanupCandidateDto = {
    /**
     * Stable identifier (the shared content path).
     */
    id: string;
    files: Array<ScannedFileDto>;
    /**
     * length > 1 means cross-seed.
     */
    torrents: Array<MatchedTorrentDto>;
    crossSeed: boolean;
    totalSizeBytes: number;
    ageDays: number;
};

export type CleanRequestDto = {
    /**
     * Absolute paths of the unused files to clean.
     */
    files: Array<string>;
    /**
     * When true (default) the downloaded data is removed from disk along with the torrent. Set to false to only remove the torrent entry.
     */
    deleteFiles?: boolean;
};

export type CleanupResultItemDto = {
    path: string;
    removedTorrents: Array<string>;
    deletedFromDisk: boolean;
    error?: string;
};

export type CleanupSummaryDto = {
    requested: number;
    cleaned: number;
    failed: number;
    removedTorrentHashes: Array<string>;
    items: Array<CleanupResultItemDto>;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    200: HealthDto;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type GetUnusedFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/files/unused';
};

export type GetUnusedFilesResponses = {
    200: Array<CleanupCandidateDto>;
};

export type GetUnusedFilesResponse = GetUnusedFilesResponses[keyof GetUnusedFilesResponses];

export type ScanFilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/files/scan';
};

export type ScanFilesResponses = {
    200: Array<CleanupCandidateDto>;
};

export type ScanFilesResponse = ScanFilesResponses[keyof ScanFilesResponses];

export type CleanFilesData = {
    body: CleanRequestDto;
    path?: never;
    query?: never;
    url: '/files/clean';
};

export type CleanFilesResponses = {
    200: CleanupSummaryDto;
};

export type CleanFilesResponse = CleanFilesResponses[keyof CleanFilesResponses];
