// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zHealthDto = z.object({
    status: z.string()
});

export const zScannedFileDto = z.object({
    path: z.string(),
    sizeBytes: z.number(),
    ageDays: z.number(),
    links: z.number()
});

export const zMatchedTorrentDto = z.object({
    hash: z.string(),
    name: z.string(),
    contentPath: z.string(),
    category: z.string(),
    tags: z.array(z.string()),
    sizeBytes: z.number()
});

export const zCleanupCandidateDto = z.object({
    id: z.string(),
    files: z.array(zScannedFileDto),
    torrents: z.array(zMatchedTorrentDto),
    crossSeed: z.boolean(),
    totalSizeBytes: z.number(),
    ageDays: z.number()
});

export const zCleanRequestDto = z.object({
    files: z.array(z.string()),
    deleteFiles: z.boolean().optional().default(true)
});

export const zCleanupResultItemDto = z.object({
    path: z.string(),
    removedTorrents: z.array(z.string()),
    deletedFromDisk: z.boolean(),
    error: z.string().optional()
});

export const zCleanupSummaryDto = z.object({
    requested: z.number(),
    cleaned: z.number(),
    failed: z.number(),
    removedTorrentHashes: z.array(z.string()),
    items: z.array(zCleanupResultItemDto)
});

export const zHealthCheckResponse = zHealthDto;

export const zGetUnusedFilesResponse = z.array(zCleanupCandidateDto);

export const zScanFilesResponse = z.array(zCleanupCandidateDto);

export const zCleanFilesBody = zCleanRequestDto;

export const zCleanFilesResponse = zCleanupSummaryDto;
